import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header';
import PaymentTypes from '../components/PaymentTypes';
import Cards from '../components/Cards';
import styles from '../styles/Home.module.css'
import Security from '../components/Security';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Flutterwave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <PaymentTypes />
        <Cards />
        <Security />
      </main>
    </div>
  );
}
